<?php
/**
 * AdGroupRetargetingListServiceCriterionTargetList
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;

use \ArrayAccess;
use \Yahoo\ObjectSerializer;

/**
 * AdGroupRetargetingListServiceCriterionTargetList Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AdGroupRetargetingListServiceCriterionTargetListは、ターゲットリスト情報を保持するオブジェクトです。&lt;br&gt;このフィールドは、いずれの場合でも必須です。&lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;AdGroupRetargetingListServiceCriterionTargetList is an object that holds target list information.&lt;br&gt;This field is required in any cases. &lt;/div&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdGroupRetargetingListServiceCriterionTargetList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdGroupRetargetingListServiceCriterionTargetList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'retargetingTrackId' => 'int',
        'targetListId' => 'int',
        'targetListName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'retargetingTrackId' => 'int64',
        'targetListId' => 'int64',
        'targetListName' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'retargetingTrackId' => 'retargetingTrackId',
        'targetListId' => 'targetListId',
        'targetListName' => 'targetListName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'retargetingTrackId' => 'setRetargetingTrackId',
        'targetListId' => 'setTargetListId',
        'targetListName' => 'setTargetListName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'retargetingTrackId' => 'getRetargetingTrackId',
        'targetListId' => 'getTargetListId',
        'targetListName' => 'getTargetListName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['retargetingTrackId'] = isset($data['retargetingTrackId']) ? $data['retargetingTrackId'] : null;
        $this->container['targetListId'] = isset($data['targetListId']) ? $data['targetListId'] : null;
        $this->container['targetListName'] = isset($data['targetListName']) ? $data['targetListName'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets retargetingTrackId
     *
     * @return int|null
     */
    public function getRetargetingTrackId()
    {
        return $this->container['retargetingTrackId'];
    }

    /**
     * Sets retargetingTrackId
     *
     * @param int|null $retargetingTrackId <div lang=\"ja\">リターゲティングトラックIDです。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Retargeting Track ID.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setRetargetingTrackId($retargetingTrackId)
    {
        $this->container['retargetingTrackId'] = $retargetingTrackId;

        return $this;
    }

    /**
     * Gets targetListId
     *
     * @return int|null
     */
    public function getTargetListId()
    {
        return $this->container['targetListId'];
    }

    /**
     * Sets targetListId
     *
     * @param int|null $targetListId <div lang=\"ja\">ターゲットリストIDです。<br>このフィールドは、いずれの場合でも必須です。</div><div lang=\"en\">Target list ID.<br>This field is required in any cases. </div>
     *
     * @return $this
     */
    public function setTargetListId($targetListId)
    {
        $this->container['targetListId'] = $targetListId;

        return $this;
    }

    /**
     * Gets targetListName
     *
     * @return string|null
     */
    public function getTargetListName()
    {
        return $this->container['targetListName'];
    }

    /**
     * Sets targetListName
     *
     * @param string|null $targetListName <div lang=\"ja\">ターゲットリスト名です。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Target list name.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setTargetListName($targetListName)
    {
        $this->container['targetListName'] = $targetListName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


