<?php
/**
 * AdGroup
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;

use \ArrayAccess;
use \Yahoo\ObjectSerializer;

/**
 * AdGroup Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AdGroup オブジェクトは、広告グループを表します。&lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;AdGroup object describes ad group information.&lt;/div&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdGroup implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdGroup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'accountId' => 'int',
        'adGroupAdRotationMode' => '\Yahoo\Model\AdGroupServiceAdGroupAdRotationMode',
        'adGroupId' => 'int',
        'adGroupName' => 'string',
        'adGroupTrackId' => 'int',
        'bid' => '\Yahoo\Model\AdGroupServiceBid',
        'campaignId' => 'int',
        'campaignName' => 'string',
        'campaignTrackId' => 'int',
        'customParameters' => '\Yahoo\Model\AdGroupServiceCustomParameters',
        'labels' => '\Yahoo\Model\AdGroupServiceLabel[]',
        'settings' => '\Yahoo\Model\AdGroupServiceSettings',
        'trackingUrl' => 'string',
        'urlReviewData' => '\Yahoo\Model\AdGroupServiceUrlReviewData',
        'userStatus' => '\Yahoo\Model\AdGroupServiceUserStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'accountId' => 'int64',
        'adGroupAdRotationMode' => null,
        'adGroupId' => 'int64',
        'adGroupName' => null,
        'adGroupTrackId' => 'int64',
        'bid' => null,
        'campaignId' => 'int64',
        'campaignName' => null,
        'campaignTrackId' => 'int64',
        'customParameters' => null,
        'labels' => null,
        'settings' => null,
        'trackingUrl' => null,
        'urlReviewData' => null,
        'userStatus' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountId' => 'accountId',
        'adGroupAdRotationMode' => 'adGroupAdRotationMode',
        'adGroupId' => 'adGroupId',
        'adGroupName' => 'adGroupName',
        'adGroupTrackId' => 'adGroupTrackId',
        'bid' => 'bid',
        'campaignId' => 'campaignId',
        'campaignName' => 'campaignName',
        'campaignTrackId' => 'campaignTrackId',
        'customParameters' => 'customParameters',
        'labels' => 'labels',
        'settings' => 'settings',
        'trackingUrl' => 'trackingUrl',
        'urlReviewData' => 'urlReviewData',
        'userStatus' => 'userStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountId' => 'setAccountId',
        'adGroupAdRotationMode' => 'setAdGroupAdRotationMode',
        'adGroupId' => 'setAdGroupId',
        'adGroupName' => 'setAdGroupName',
        'adGroupTrackId' => 'setAdGroupTrackId',
        'bid' => 'setBid',
        'campaignId' => 'setCampaignId',
        'campaignName' => 'setCampaignName',
        'campaignTrackId' => 'setCampaignTrackId',
        'customParameters' => 'setCustomParameters',
        'labels' => 'setLabels',
        'settings' => 'setSettings',
        'trackingUrl' => 'setTrackingUrl',
        'urlReviewData' => 'setUrlReviewData',
        'userStatus' => 'setUserStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountId' => 'getAccountId',
        'adGroupAdRotationMode' => 'getAdGroupAdRotationMode',
        'adGroupId' => 'getAdGroupId',
        'adGroupName' => 'getAdGroupName',
        'adGroupTrackId' => 'getAdGroupTrackId',
        'bid' => 'getBid',
        'campaignId' => 'getCampaignId',
        'campaignName' => 'getCampaignName',
        'campaignTrackId' => 'getCampaignTrackId',
        'customParameters' => 'getCustomParameters',
        'labels' => 'getLabels',
        'settings' => 'getSettings',
        'trackingUrl' => 'getTrackingUrl',
        'urlReviewData' => 'getUrlReviewData',
        'userStatus' => 'getUserStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accountId'] = isset($data['accountId']) ? $data['accountId'] : null;
        $this->container['adGroupAdRotationMode'] = isset($data['adGroupAdRotationMode']) ? $data['adGroupAdRotationMode'] : null;
        $this->container['adGroupId'] = isset($data['adGroupId']) ? $data['adGroupId'] : null;
        $this->container['adGroupName'] = isset($data['adGroupName']) ? $data['adGroupName'] : null;
        $this->container['adGroupTrackId'] = isset($data['adGroupTrackId']) ? $data['adGroupTrackId'] : null;
        $this->container['bid'] = isset($data['bid']) ? $data['bid'] : null;
        $this->container['campaignId'] = isset($data['campaignId']) ? $data['campaignId'] : null;
        $this->container['campaignName'] = isset($data['campaignName']) ? $data['campaignName'] : null;
        $this->container['campaignTrackId'] = isset($data['campaignTrackId']) ? $data['campaignTrackId'] : null;
        $this->container['customParameters'] = isset($data['customParameters']) ? $data['customParameters'] : null;
        $this->container['labels'] = isset($data['labels']) ? $data['labels'] : null;
        $this->container['settings'] = isset($data['settings']) ? $data['settings'] : null;
        $this->container['trackingUrl'] = isset($data['trackingUrl']) ? $data['trackingUrl'] : null;
        $this->container['urlReviewData'] = isset($data['urlReviewData']) ? $data['urlReviewData'] : null;
        $this->container['userStatus'] = isset($data['userStatus']) ? $data['userStatus'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountId
     *
     * @return int|null
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param int|null $accountId <div lang=\"ja\">アカウントIDです。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Account ID.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setAccountId($accountId)
    {
        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets adGroupAdRotationMode
     *
     * @return \Yahoo\Model\AdGroupServiceAdGroupAdRotationMode|null
     */
    public function getAdGroupAdRotationMode()
    {
        return $this->container['adGroupAdRotationMode'];
    }

    /**
     * Sets adGroupAdRotationMode
     *
     * @param \Yahoo\Model\AdGroupServiceAdGroupAdRotationMode|null $adGroupAdRotationMode adGroupAdRotationMode
     *
     * @return $this
     */
    public function setAdGroupAdRotationMode($adGroupAdRotationMode)
    {
        $this->container['adGroupAdRotationMode'] = $adGroupAdRotationMode;

        return $this;
    }

    /**
     * Gets adGroupId
     *
     * @return int|null
     */
    public function getAdGroupId()
    {
        return $this->container['adGroupId'];
    }

    /**
     * Sets adGroupId
     *
     * @param int|null $adGroupId <div lang=\"ja\">広告グループIDです。<br>このフィールドは、ADD時は無視され、SETおよびREMOVE時は必須となります。</div><div lang=\"en\">Ad group ID.<br>This field will be ignored in ADD operation, and will be required in SET and REMOVE operation.</div>
     *
     * @return $this
     */
    public function setAdGroupId($adGroupId)
    {
        $this->container['adGroupId'] = $adGroupId;

        return $this;
    }

    /**
     * Gets adGroupName
     *
     * @return string|null
     */
    public function getAdGroupName()
    {
        return $this->container['adGroupName'];
    }

    /**
     * Sets adGroupName
     *
     * @param string|null $adGroupName <div lang=\"ja\">広告グループ名です。<br>このフィールドは、ADD時は必須となり、SET時は省略可能となります。</div><div lang=\"en\">Ad Group name.<br>This field is required in ADD operation, and will be optional in SET operation.</div>
     *
     * @return $this
     */
    public function setAdGroupName($adGroupName)
    {
        $this->container['adGroupName'] = $adGroupName;

        return $this;
    }

    /**
     * Gets adGroupTrackId
     *
     * @return int|null
     */
    public function getAdGroupTrackId()
    {
        return $this->container['adGroupTrackId'];
    }

    /**
     * Sets adGroupTrackId
     *
     * @param int|null $adGroupTrackId <div lang=\"ja\">トラッキング用広告グループIDです。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Ad Group ID for tracking.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setAdGroupTrackId($adGroupTrackId)
    {
        $this->container['adGroupTrackId'] = $adGroupTrackId;

        return $this;
    }

    /**
     * Gets bid
     *
     * @return \Yahoo\Model\AdGroupServiceBid|null
     */
    public function getBid()
    {
        return $this->container['bid'];
    }

    /**
     * Sets bid
     *
     * @param \Yahoo\Model\AdGroupServiceBid|null $bid bid
     *
     * @return $this
     */
    public function setBid($bid)
    {
        $this->container['bid'] = $bid;

        return $this;
    }

    /**
     * Gets campaignId
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaignId'];
    }

    /**
     * Sets campaignId
     *
     * @param int|null $campaignId <div lang=\"ja\">キャンペーンIDです。<br>このフィールドは、いずれの場合でも必須となります。</div><div lang=\"en\">Campaign ID.<br>This field is required in any cases.</div>
     *
     * @return $this
     */
    public function setCampaignId($campaignId)
    {
        $this->container['campaignId'] = $campaignId;

        return $this;
    }

    /**
     * Gets campaignName
     *
     * @return string|null
     */
    public function getCampaignName()
    {
        return $this->container['campaignName'];
    }

    /**
     * Sets campaignName
     *
     * @param string|null $campaignName <div lang=\"ja\">キャンペーン名です。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Campaign name.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setCampaignName($campaignName)
    {
        $this->container['campaignName'] = $campaignName;

        return $this;
    }

    /**
     * Gets campaignTrackId
     *
     * @return int|null
     */
    public function getCampaignTrackId()
    {
        return $this->container['campaignTrackId'];
    }

    /**
     * Sets campaignTrackId
     *
     * @param int|null $campaignTrackId <div lang=\"ja\">トラッキング用キャンペーンIDです。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div><div lang=\"en\">Campaign ID for tracking.<br>Although this field will be returned in the response, it will be ignored on input. </div>
     *
     * @return $this
     */
    public function setCampaignTrackId($campaignTrackId)
    {
        $this->container['campaignTrackId'] = $campaignTrackId;

        return $this;
    }

    /**
     * Gets customParameters
     *
     * @return \Yahoo\Model\AdGroupServiceCustomParameters|null
     */
    public function getCustomParameters()
    {
        return $this->container['customParameters'];
    }

    /**
     * Sets customParameters
     *
     * @param \Yahoo\Model\AdGroupServiceCustomParameters|null $customParameters customParameters
     *
     * @return $this
     */
    public function setCustomParameters($customParameters)
    {
        $this->container['customParameters'] = $customParameters;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \Yahoo\Model\AdGroupServiceLabel[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \Yahoo\Model\AdGroupServiceLabel[]|null $labels labels
     *
     * @return $this
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Yahoo\Model\AdGroupServiceSettings|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Yahoo\Model\AdGroupServiceSettings|null $settings settings
     *
     * @return $this
     */
    public function setSettings($settings)
    {
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets trackingUrl
     *
     * @return string|null
     */
    public function getTrackingUrl()
    {
        return $this->container['trackingUrl'];
    }

    /**
     * Sets trackingUrl
     *
     * @param string|null $trackingUrl <div lang=\"ja\">トラッキングURLです。<br>このフィールドは、省略可能となります。<br>※キャンペーンがアプリキャンペーンでAndroidの場合、設定はできません。<br>※SET時、こちらが審査中の場合、編集はできません。また、変更がない場合、審査対象とはなりません。</div><div lang=\"en\">Tracking URL.<br>This field is optional.<br>*Cannot set for a Mobile App campaign for Android OS.<br>*In SET operation, cannot update it when this field is in editorial review. In addition, if there is no change, it will not to be reviewed.</div>
     *
     * @return $this
     */
    public function setTrackingUrl($trackingUrl)
    {
        $this->container['trackingUrl'] = $trackingUrl;

        return $this;
    }

    /**
     * Gets urlReviewData
     *
     * @return \Yahoo\Model\AdGroupServiceUrlReviewData|null
     */
    public function getUrlReviewData()
    {
        return $this->container['urlReviewData'];
    }

    /**
     * Sets urlReviewData
     *
     * @param \Yahoo\Model\AdGroupServiceUrlReviewData|null $urlReviewData urlReviewData
     *
     * @return $this
     */
    public function setUrlReviewData($urlReviewData)
    {
        $this->container['urlReviewData'] = $urlReviewData;

        return $this;
    }

    /**
     * Gets userStatus
     *
     * @return \Yahoo\Model\AdGroupServiceUserStatus|null
     */
    public function getUserStatus()
    {
        return $this->container['userStatus'];
    }

    /**
     * Sets userStatus
     *
     * @param \Yahoo\Model\AdGroupServiceUserStatus|null $userStatus userStatus
     *
     * @return $this
     */
    public function setUserStatus($userStatus)
    {
        $this->container['userStatus'] = $userStatus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


