<?php
/**
 * BiddingStrategyServiceTargetCpaBiddingScheme
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;

use \ArrayAccess;
use \Yahoo\ObjectSerializer;

/**
 * BiddingStrategyServiceTargetCpaBiddingScheme Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;BiddingStrategyServiceTargetCpaBiddingSchemeオブジェクトは、コンバージョン単価の目標値の自動入札設定情報を表します。&lt;br&gt;このフィールドは、省略可能となります。※ADD時、typeがTARGET_CPAの場合は必須です。&lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;BiddingStrategyServiceTargetCpaBiddingScheme  object displays Auto Bidding setting for Target CPA.&lt;br&gt;This field is optional. *If type is &#39;TARGET_CPA&#39;, this field is required in ADD operation. &lt;/div&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BiddingStrategyServiceTargetCpaBiddingScheme implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BiddingStrategyServiceTargetCpaBiddingScheme';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bidCeiling' => 'int',
        'bidFloor' => 'int',
        'targetCpa' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'bidCeiling' => 'int64',
        'bidFloor' => 'int64',
        'targetCpa' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bidCeiling' => 'bidCeiling',
        'bidFloor' => 'bidFloor',
        'targetCpa' => 'targetCpa'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bidCeiling' => 'setBidCeiling',
        'bidFloor' => 'setBidFloor',
        'targetCpa' => 'setTargetCpa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bidCeiling' => 'getBidCeiling',
        'bidFloor' => 'getBidFloor',
        'targetCpa' => 'getTargetCpa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bidCeiling'] = isset($data['bidCeiling']) ? $data['bidCeiling'] : null;
        $this->container['bidFloor'] = isset($data['bidFloor']) ? $data['bidFloor'] : null;
        $this->container['targetCpa'] = isset($data['targetCpa']) ? $data['targetCpa'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bidCeiling
     *
     * @return int|null
     */
    public function getBidCeiling()
    {
        return $this->container['bidCeiling'];
    }

    /**
     * Sets bidCeiling
     *
     * @param int|null $bidCeiling <div lang=\"ja\">入札価格の上限です。<br>※「0」が設定された場合、上限設定はありません。<br>このフィールドは、いずれの場合でも省略可能となります。</div><div lang=\"en\">CPC limit.<br>* No limits if &#34;0&#34; is set.<br>This field is optional in any cases. </div>
     *
     * @return $this
     */
    public function setBidCeiling($bidCeiling)
    {
        $this->container['bidCeiling'] = $bidCeiling;

        return $this;
    }

    /**
     * Gets bidFloor
     *
     * @return int|null
     */
    public function getBidFloor()
    {
        return $this->container['bidFloor'];
    }

    /**
     * Sets bidFloor
     *
     * @param int|null $bidFloor <div lang=\"ja\">入札価格の下限です。<br>※ 設定を解除する場合は「0」を指定します。<br>このフィールドは、いずれの場合でも省略可能となります。</div><div lang=\"en\">Minimum CPC.<br>* Set  &#34;0&#34; to deactivate.<br>This field is optional in any cases. </div>
     *
     * @return $this
     */
    public function setBidFloor($bidFloor)
    {
        $this->container['bidFloor'] = $bidFloor;

        return $this;
    }

    /**
     * Gets targetCpa
     *
     * @return int|null
     */
    public function getTargetCpa()
    {
        return $this->container['targetCpa'];
    }

    /**
     * Sets targetCpa
     *
     * @param int|null $targetCpa <div lang=\"ja\">コンバージョン単価の目標値です（日本円です）。<br>このフィールドは、ADD時は必須となり、SET時は省略可能となります。</div><div lang=\"en\">Target CPA (JPY).<br>This field is required in ADD operation, and will be optional in SET operation. </div>
     *
     * @return $this
     */
    public function setTargetCpa($targetCpa)
    {
        $this->container['targetCpa'] = $targetCpa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


