<?php
/**
 * BidLandscape
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;

use \ArrayAccess;
use \Yahoo\ObjectSerializer;

/**
 * BidLandscape Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;BidLandscapeオブジェクトは、予測結果を表します。&lt;/div&gt;&lt;br&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;Expected results.&lt;/div&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BidLandscape implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BidLandscape';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'campaignId' => 'int',
        'adGroupId' => 'int',
        'startDate' => 'string',
        'endDate' => 'string',
        'landscapePoints' => '\Yahoo\Model\BidLandscapeServicePoints[]',
        'bidLandscapeType' => 'string',
        'adGroupBidLandscape' => '\Yahoo\Model\BidLandscapeServiceAdGroupBidLandscape',
        'criterionBidLandscape' => '\Yahoo\Model\BidLandscapeServiceCriterionBidLandscape'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'campaignId' => 'int64',
        'adGroupId' => 'int64',
        'startDate' => null,
        'endDate' => null,
        'landscapePoints' => null,
        'bidLandscapeType' => null,
        'adGroupBidLandscape' => null,
        'criterionBidLandscape' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'campaignId' => 'campaignId',
        'adGroupId' => 'adGroupId',
        'startDate' => 'startDate',
        'endDate' => 'endDate',
        'landscapePoints' => 'landscapePoints',
        'bidLandscapeType' => 'bidLandscapeType',
        'adGroupBidLandscape' => 'adGroupBidLandscape',
        'criterionBidLandscape' => 'criterionBidLandscape'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'campaignId' => 'setCampaignId',
        'adGroupId' => 'setAdGroupId',
        'startDate' => 'setStartDate',
        'endDate' => 'setEndDate',
        'landscapePoints' => 'setLandscapePoints',
        'bidLandscapeType' => 'setBidLandscapeType',
        'adGroupBidLandscape' => 'setAdGroupBidLandscape',
        'criterionBidLandscape' => 'setCriterionBidLandscape'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'campaignId' => 'getCampaignId',
        'adGroupId' => 'getAdGroupId',
        'startDate' => 'getStartDate',
        'endDate' => 'getEndDate',
        'landscapePoints' => 'getLandscapePoints',
        'bidLandscapeType' => 'getBidLandscapeType',
        'adGroupBidLandscape' => 'getAdGroupBidLandscape',
        'criterionBidLandscape' => 'getCriterionBidLandscape'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['campaignId'] = isset($data['campaignId']) ? $data['campaignId'] : null;
        $this->container['adGroupId'] = isset($data['adGroupId']) ? $data['adGroupId'] : null;
        $this->container['startDate'] = isset($data['startDate']) ? $data['startDate'] : null;
        $this->container['endDate'] = isset($data['endDate']) ? $data['endDate'] : null;
        $this->container['landscapePoints'] = isset($data['landscapePoints']) ? $data['landscapePoints'] : null;
        $this->container['bidLandscapeType'] = isset($data['bidLandscapeType']) ? $data['bidLandscapeType'] : null;
        $this->container['adGroupBidLandscape'] = isset($data['adGroupBidLandscape']) ? $data['adGroupBidLandscape'] : null;
        $this->container['criterionBidLandscape'] = isset($data['criterionBidLandscape']) ? $data['criterionBidLandscape'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets campaignId
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaignId'];
    }

    /**
     * Sets campaignId
     *
     * @param int|null $campaignId <div lang=\"ja\">キャンペーンIDです。</div><br><div lang=\"en\">Campaign ID.</div>
     *
     * @return $this
     */
    public function setCampaignId($campaignId)
    {
        $this->container['campaignId'] = $campaignId;

        return $this;
    }

    /**
     * Gets adGroupId
     *
     * @return int|null
     */
    public function getAdGroupId()
    {
        return $this->container['adGroupId'];
    }

    /**
     * Sets adGroupId
     *
     * @param int|null $adGroupId <div lang=\"ja\">広告グループIDです。</div><br><div lang=\"en\">Ad Gropup ID.</div>
     *
     * @return $this
     */
    public function setAdGroupId($adGroupId)
    {
        $this->container['adGroupId'] = $adGroupId;

        return $this;
    }

    /**
     * Gets startDate
     *
     * @return string|null
     */
    public function getStartDate()
    {
        return $this->container['startDate'];
    }

    /**
     * Sets startDate
     *
     * @param string|null $startDate <div lang=\"ja\">開始日です。</div><br><div lang=\"en\">Start date.</div>
     *
     * @return $this
     */
    public function setStartDate($startDate)
    {
        $this->container['startDate'] = $startDate;

        return $this;
    }

    /**
     * Gets endDate
     *
     * @return string|null
     */
    public function getEndDate()
    {
        return $this->container['endDate'];
    }

    /**
     * Sets endDate
     *
     * @param string|null $endDate <div lang=\"ja\">終了日です。</div><br><div lang=\"en\">End date.</div>
     *
     * @return $this
     */
    public function setEndDate($endDate)
    {
        $this->container['endDate'] = $endDate;

        return $this;
    }

    /**
     * Gets landscapePoints
     *
     * @return \Yahoo\Model\BidLandscapeServicePoints[]|null
     */
    public function getLandscapePoints()
    {
        return $this->container['landscapePoints'];
    }

    /**
     * Sets landscapePoints
     *
     * @param \Yahoo\Model\BidLandscapeServicePoints[]|null $landscapePoints landscapePoints
     *
     * @return $this
     */
    public function setLandscapePoints($landscapePoints)
    {
        $this->container['landscapePoints'] = $landscapePoints;

        return $this;
    }

    /**
     * Gets bidLandscapeType
     *
     * @return string|null
     */
    public function getBidLandscapeType()
    {
        return $this->container['bidLandscapeType'];
    }

    /**
     * Sets bidLandscapeType
     *
     * @param string|null $bidLandscapeType <div lang=\"ja\">BidLandscape のサブタイプを示します。</div><br><div lang=\"en\">The subtype of BidLandscape.</div>
     *
     * @return $this
     */
    public function setBidLandscapeType($bidLandscapeType)
    {
        $this->container['bidLandscapeType'] = $bidLandscapeType;

        return $this;
    }

    /**
     * Gets adGroupBidLandscape
     *
     * @return \Yahoo\Model\BidLandscapeServiceAdGroupBidLandscape|null
     */
    public function getAdGroupBidLandscape()
    {
        return $this->container['adGroupBidLandscape'];
    }

    /**
     * Sets adGroupBidLandscape
     *
     * @param \Yahoo\Model\BidLandscapeServiceAdGroupBidLandscape|null $adGroupBidLandscape adGroupBidLandscape
     *
     * @return $this
     */
    public function setAdGroupBidLandscape($adGroupBidLandscape)
    {
        $this->container['adGroupBidLandscape'] = $adGroupBidLandscape;

        return $this;
    }

    /**
     * Gets criterionBidLandscape
     *
     * @return \Yahoo\Model\BidLandscapeServiceCriterionBidLandscape|null
     */
    public function getCriterionBidLandscape()
    {
        return $this->container['criterionBidLandscape'];
    }

    /**
     * Sets criterionBidLandscape
     *
     * @param \Yahoo\Model\BidLandscapeServiceCriterionBidLandscape|null $criterionBidLandscape criterionBidLandscape
     *
     * @return $this
     */
    public function setCriterionBidLandscape($criterionBidLandscape)
    {
        $this->container['criterionBidLandscape'] = $criterionBidLandscape;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


