<?php
/**
 * CampaignServiceConversionOptimizerEligibility
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;
use \Yahoo\ObjectSerializer;

/**
 * CampaignServiceConversionOptimizerEligibility Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;CampaignServiceConversionOptimizerEligibilityは、コンバージョンオプティマイザーが利用可能であるか判定します。&lt;br&gt;このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 &lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;CampaignServiceConversionOptimizerEligibility object is to determine if it is possible to use conversion optimizer.&lt;br&gt;Although this field will be returned in the response, it will be ignored on input. &lt;/div&gt;&lt;hr&gt; &lt;p&gt;* &lt;code&gt;ENABLE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;利用可能です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Can use conversion optimizer.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;DISABLE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;利用できません。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Cannot use conversion optimizer.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;CAMPAIGN_IS_NOT_ACTIVE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キャンペーンがアクティブではありません。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Campaign is not active.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;NOT_CPC_CAMPAIGN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;コンバージョンオプティマイザーは、手動入札の場合にのみ有効です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Valid when it is in manual bidding.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;CONVERSION_TRACKING_NOT_ENABLED&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;コンバージョン測定タグが発行されていません。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Conversion tracking tag is not enabled yet.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;NOT_ENOUGH_CONVERSIONS&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;コンバージョンの実績が十分ではありません。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Conversion performance is not enough.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CampaignServiceConversionOptimizerEligibility
{
    /**
     * Possible values of this enum
     */
    const ENABLE = 'ENABLE';
    const DISABLE = 'DISABLE';
    const CAMPAIGN_IS_NOT_ACTIVE = 'CAMPAIGN_IS_NOT_ACTIVE';
    const NOT_CPC_CAMPAIGN = 'NOT_CPC_CAMPAIGN';
    const CONVERSION_TRACKING_NOT_ENABLED = 'CONVERSION_TRACKING_NOT_ENABLED';
    const NOT_ENOUGH_CONVERSIONS = 'NOT_ENOUGH_CONVERSIONS';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENABLE,
            self::DISABLE,
            self::CAMPAIGN_IS_NOT_ACTIVE,
            self::NOT_CPC_CAMPAIGN,
            self::CONVERSION_TRACKING_NOT_ENABLED,
            self::NOT_ENOUGH_CONVERSIONS,
            self::UNKNOWN,
        ];
    }
}


