<?php
/**
 * CampaignServiceSettingType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Model;
use \Yahoo\ObjectSerializer;

/**
 * CampaignServiceSettingType Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;CampaignServiceSettingTypeは、キャンペーンのターゲティング設定情報を表します。&lt;br&gt;ADD時、このフィールドは省略可能となります。その際、デフォルト設定値はGEO_TARGET_TYPE_SETTINGとなります。&lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;CampaignServiceSettingType describes the setting information of Target on the campaign.&lt;br&gt;This field is optional in ADD operation. The default value will be GEO_TARGET_TYPE_SETTING. &lt;/div&gt;&lt;hr&gt; &lt;p&gt;* &lt;code&gt;GEO_TARGET_TYPE_SETTING&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キャンペーンの地域ターゲットの設定です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Setting of Geographic Targeting on the Campaign.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;TARGET_LIST_SETTING&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;サイトリターゲティングの設定です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Setting of Site Retargeting.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;DYNAMIC_ADS_FOR_SEARCH_SETTING&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;動的検索連動型広告の設定です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Setting of Dynamic ads for search.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CampaignServiceSettingType
{
    /**
     * Possible values of this enum
     */
    const GEO_TARGET_TYPE_SETTING = 'GEO_TARGET_TYPE_SETTING';
    const TARGET_LIST_SETTING = 'TARGET_LIST_SETTING';
    const DYNAMIC_ADS_FOR_SEARCH_SETTING = 'DYNAMIC_ADS_FOR_SEARCH_SETTING';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GEO_TARGET_TYPE_SETTING,
            self::TARGET_LIST_SETTING,
            self::DYNAMIC_ADS_FOR_SEARCH_SETTING,
            self::UNKNOWN,
        ];
    }
}


