<?php
/**
 * AdGroupAdServiceApi
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Yahoo\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Yahoo\ApiException;
use Yahoo\Configuration;
use Yahoo\HeaderSelector;
use Yahoo\ObjectSerializer;

/**
 * AdGroupAdServiceApi Class Doc Comment
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdGroupAdServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation adGroupAdServiceAddPost
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\Yahoo\Model\AdGroupAdServiceMutateResponse
     */
    public function adGroupAdServiceAddPost($adGroupAdServiceOperation = null)
    {
        list($response) = $this->adGroupAdServiceAddPostWithHttpInfo($adGroupAdServiceOperation);
        return $response;
    }

    /**
     * Operation adGroupAdServiceAddPostWithHttpInfo
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\Yahoo\Model\AdGroupAdServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupAdServiceAddPostWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $request = $this->adGroupAdServiceAddPostRequest($adGroupAdServiceOperation);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Yahoo\Model\AdGroupAdServiceMutateResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Yahoo\Model\AdGroupAdServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yahoo\Model\AdGroupAdServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupAdServiceAddPostAsync
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceAddPostAsync($adGroupAdServiceOperation = null)
    {
        return $this->adGroupAdServiceAddPostAsyncWithHttpInfo($adGroupAdServiceOperation)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupAdServiceAddPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceAddPostAsyncWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
        $request = $this->adGroupAdServiceAddPostRequest($adGroupAdServiceOperation);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupAdServiceAddPost'
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function adGroupAdServiceAddPostRequest($adGroupAdServiceOperation = null)
    {

        $resourcePath = '/AdGroupAdService/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($adGroupAdServiceOperation)) {
            $_tempBody = $adGroupAdServiceOperation;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupAdServiceGetPost
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSelector $adGroupAdServiceSelector adGroupAdServiceSelector (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\Yahoo\Model\AdGroupAdServiceGetResponse
     */
    public function adGroupAdServiceGetPost($adGroupAdServiceSelector = null)
    {
        list($response) = $this->adGroupAdServiceGetPostWithHttpInfo($adGroupAdServiceSelector);
        return $response;
    }

    /**
     * Operation adGroupAdServiceGetPostWithHttpInfo
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSelector $adGroupAdServiceSelector (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\Yahoo\Model\AdGroupAdServiceGetResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupAdServiceGetPostWithHttpInfo($adGroupAdServiceSelector = null)
    {
        $request = $this->adGroupAdServiceGetPostRequest($adGroupAdServiceSelector);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Yahoo\Model\AdGroupAdServiceGetResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Yahoo\Model\AdGroupAdServiceGetResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Yahoo\Model\AdGroupAdServiceGetResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yahoo\Model\AdGroupAdServiceGetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupAdServiceGetPostAsync
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSelector $adGroupAdServiceSelector (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceGetPostAsync($adGroupAdServiceSelector = null)
    {
        return $this->adGroupAdServiceGetPostAsyncWithHttpInfo($adGroupAdServiceSelector)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupAdServiceGetPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSelector $adGroupAdServiceSelector (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceGetPostAsyncWithHttpInfo($adGroupAdServiceSelector = null)
    {
        $returnType = '\Yahoo\Model\AdGroupAdServiceGetResponse';
        $request = $this->adGroupAdServiceGetPostRequest($adGroupAdServiceSelector);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupAdServiceGetPost'
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSelector $adGroupAdServiceSelector (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function adGroupAdServiceGetPostRequest($adGroupAdServiceSelector = null)
    {

        $resourcePath = '/AdGroupAdService/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($adGroupAdServiceSelector)) {
            $_tempBody = $adGroupAdServiceSelector;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupAdServiceRemovePost
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\Yahoo\Model\AdGroupAdServiceMutateResponse
     */
    public function adGroupAdServiceRemovePost($adGroupAdServiceOperation = null)
    {
        list($response) = $this->adGroupAdServiceRemovePostWithHttpInfo($adGroupAdServiceOperation);
        return $response;
    }

    /**
     * Operation adGroupAdServiceRemovePostWithHttpInfo
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\Yahoo\Model\AdGroupAdServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupAdServiceRemovePostWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $request = $this->adGroupAdServiceRemovePostRequest($adGroupAdServiceOperation);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Yahoo\Model\AdGroupAdServiceMutateResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Yahoo\Model\AdGroupAdServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yahoo\Model\AdGroupAdServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupAdServiceRemovePostAsync
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceRemovePostAsync($adGroupAdServiceOperation = null)
    {
        return $this->adGroupAdServiceRemovePostAsyncWithHttpInfo($adGroupAdServiceOperation)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupAdServiceRemovePostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceRemovePostAsyncWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
        $request = $this->adGroupAdServiceRemovePostRequest($adGroupAdServiceOperation);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupAdServiceRemovePost'
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function adGroupAdServiceRemovePostRequest($adGroupAdServiceOperation = null)
    {

        $resourcePath = '/AdGroupAdService/remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($adGroupAdServiceOperation)) {
            $_tempBody = $adGroupAdServiceOperation;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupAdServiceSetPost
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\Yahoo\Model\AdGroupAdServiceMutateResponse
     */
    public function adGroupAdServiceSetPost($adGroupAdServiceOperation = null)
    {
        list($response) = $this->adGroupAdServiceSetPostWithHttpInfo($adGroupAdServiceOperation);
        return $response;
    }

    /**
     * Operation adGroupAdServiceSetPostWithHttpInfo
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\Yahoo\Model\AdGroupAdServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupAdServiceSetPostWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $request = $this->adGroupAdServiceSetPostRequest($adGroupAdServiceOperation);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Yahoo\Model\AdGroupAdServiceMutateResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Yahoo\Model\AdGroupAdServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yahoo\Model\AdGroupAdServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupAdServiceSetPostAsync
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceSetPostAsync($adGroupAdServiceOperation = null)
    {
        return $this->adGroupAdServiceSetPostAsyncWithHttpInfo($adGroupAdServiceOperation)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupAdServiceSetPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceSetPostAsyncWithHttpInfo($adGroupAdServiceOperation = null)
    {
        $returnType = '\Yahoo\Model\AdGroupAdServiceMutateResponse';
        $request = $this->adGroupAdServiceSetPostRequest($adGroupAdServiceOperation);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupAdServiceSetPost'
     *
     * @param  \Yahoo\Model\AdGroupAdServiceOperation $adGroupAdServiceOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function adGroupAdServiceSetPostRequest($adGroupAdServiceOperation = null)
    {

        $resourcePath = '/AdGroupAdService/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($adGroupAdServiceOperation)) {
            $_tempBody = $adGroupAdServiceOperation;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupAdServiceSetTrademarkStatusPost
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSetTrademarkStatusOperation $adGroupAdServiceSetTrademarkStatusOperation adGroupAdServiceSetTrademarkStatusOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse
     */
    public function adGroupAdServiceSetTrademarkStatusPost($adGroupAdServiceSetTrademarkStatusOperation = null)
    {
        list($response) = $this->adGroupAdServiceSetTrademarkStatusPostWithHttpInfo($adGroupAdServiceSetTrademarkStatusOperation);
        return $response;
    }

    /**
     * Operation adGroupAdServiceSetTrademarkStatusPostWithHttpInfo
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSetTrademarkStatusOperation $adGroupAdServiceSetTrademarkStatusOperation (optional)
     *
     * @throws \Yahoo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupAdServiceSetTrademarkStatusPostWithHttpInfo($adGroupAdServiceSetTrademarkStatusOperation = null)
    {
        $request = $this->adGroupAdServiceSetTrademarkStatusPostRequest($adGroupAdServiceSetTrademarkStatusOperation);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupAdServiceSetTrademarkStatusPostAsync
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSetTrademarkStatusOperation $adGroupAdServiceSetTrademarkStatusOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceSetTrademarkStatusPostAsync($adGroupAdServiceSetTrademarkStatusOperation = null)
    {
        return $this->adGroupAdServiceSetTrademarkStatusPostAsyncWithHttpInfo($adGroupAdServiceSetTrademarkStatusOperation)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupAdServiceSetTrademarkStatusPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSetTrademarkStatusOperation $adGroupAdServiceSetTrademarkStatusOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupAdServiceSetTrademarkStatusPostAsyncWithHttpInfo($adGroupAdServiceSetTrademarkStatusOperation = null)
    {
        $returnType = '\Yahoo\Model\AdGroupAdServiceSetTrademarkStatusResponse';
        $request = $this->adGroupAdServiceSetTrademarkStatusPostRequest($adGroupAdServiceSetTrademarkStatusOperation);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupAdServiceSetTrademarkStatusPost'
     *
     * @param  \Yahoo\Model\AdGroupAdServiceSetTrademarkStatusOperation $adGroupAdServiceSetTrademarkStatusOperation (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function adGroupAdServiceSetTrademarkStatusPostRequest($adGroupAdServiceSetTrademarkStatusOperation = null)
    {

        $resourcePath = '/AdGroupAdService/setTrademarkStatus';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($adGroupAdServiceSetTrademarkStatusOperation)) {
            $_tempBody = $adGroupAdServiceSetTrademarkStatusOperation;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
