<?php
/**
 * CampaignTargetServiceSelectorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yahoo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-search-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Yahoo;

use PHPUnit\Framework\TestCase;

/**
 * CampaignTargetServiceSelectorTest Class Doc Comment
 *
 * @category    Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;CampaignTargetServiceSelectorオブジェクトは、操作の対象とするキャンペーンのターゲティング設定を表します。&lt;/div&gt;&lt;div lang&#x3D;\&quot;en\&quot;&gt;CampaignTargetSelector object describes the targeting settings on the campaign to be operated.&lt;/div&gt;
 * @package     Yahoo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CampaignTargetServiceSelectorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignTargetServiceSelector"
     */
    public function testCampaignTargetServiceSelector()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "campaignIds"
     */
    public function testPropertyCampaignIds()
    {
    }

    /**
     * Test attribute "excludedType"
     */
    public function testPropertyExcludedType()
    {
    }

    /**
     * Test attribute "numberResults"
     */
    public function testPropertyNumberResults()
    {
    }

    /**
     * Test attribute "platformTypes"
     */
    public function testPropertyPlatformTypes()
    {
    }

    /**
     * Test attribute "startIndex"
     */
    public function testPropertyStartIndex()
    {
    }

    /**
     * Test attribute "targetIds"
     */
    public function testPropertyTargetIds()
    {
    }

    /**
     * Test attribute "targetTypes"
     */
    public function testPropertyTargetTypes()
    {
    }
}
